In [61]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [62]:
df = pd.read_csv("../Data/Automobile_data.csv")
df.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19     3.4              10.0        102      5500       24   
4         mpfi  3.19     3.4               8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [63]:
df = df[['horsepower', 'peak-rpm', 'bore', 'stroke', 'price']]

In [64]:
X = df.drop(['price'], axis = 1)
y = df['price']

In [65]:
X.replace('?', -1, inplace = True)
for col in X.columns:
    X[col] = X[col].apply(lambda x:float(x))

In [66]:
y.replace('?', -1, inplace = True)
y = y.apply(lambda x: float(x))

In [67]:
X = sm.add_constant(X)
X.head()

const  horsepower  peak-rpm  bore  stroke
0    1.0       111.0    5000.0  3.47    2.68
1    1.0       111.0    5000.0  3.47    2.68
2    1.0       154.0    5000.0  2.68    3.47
3    1.0       102.0    5500.0  3.19    3.40
4    1.0       115.0    5500.0  3.19    3.40

In [68]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   const       205 non-null    float64
 1   horsepower  205 non-null    float64
 2   peak-rpm    205 non-null    float64
 3   bore        205 non-null    float64
 4   stroke      205 non-null    float64
dtypes: float64(5)
memory usage: 8.1 KB


In [69]:
results = sm.OLS(np.asarray(y), np.asarray(X)).fit()
print(results.params)

[ 1.38724438e+04  1.49541282e+02 -3.08797315e+00  3.97914737e+02
 -6.23771897e+02]


In [70]:
A = np.identity(len(results.params))
A = A[1:, :]

print(A)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [71]:
print(results.f_test(A))

<F test: F=59.19747800864015, p=6.573071436194563e-33, df_denom=200, df_num=4>


[F-Table Link](http://www.socr.ucla.edu/Applets.dir/F_Table.html)

#### The F-Value for these degrees of freedom is 2.3719 assuming our alpha to be 0.05

Since F_Statistic > F_Critical, we reject the null hypothesis which means that the independent variables are jointly significant in explaining the variance of the dependent variable