In [1]:
import dgl
import numpy as np
import torch

In [2]:
## Creating a Directed Graph with 5 leaves

g = dgl.graph(([0,0,0,0,0], [1,2,3,4,5]), num_nodes = 6)

In [5]:
# Prints the source and destination nodes of every edge
print(g.edges())

(tensor([0, 0, 0, 0, 0]), tensor([1, 2, 3, 4, 5]))


In [6]:
# Assign a 3 dimensional Node Feature Vector for each node
print("Before Assigning: ", g.ndata)
g.ndata['x'] = torch.randn(6, 3)
print("After Assigning: ", g.ndata)

Before Assigning:  {}
After Assigning:  {'x': tensor([[ 0.0974, -1.3089,  2.1166],
        [ 0.4933,  1.3394,  0.7622],
        [-0.4205,  1.6478, -0.8186],
        [-1.0759,  0.2161,  0.0928],
        [ 0.5373,  1.4560, -0.3428],
        [-0.3801,  0.1176, -0.2087]])}


In [8]:
## Querying Graph Structures
print(g.num_nodes())
print(g.num_edges())

#Printing Out Degrees of Node 0, ie, the center Node
print(g.out_degrees(0))

#Printing In Degrees of Node 0, ie, the center Node
print(g.in_degrees(0))

6
5
5
0


In [9]:
## Graph Transformations

#Induce a subgraph from Node 0, Node 1 and node 3 from the original graph
sg1 = g.subgraph([0, 1, 3])

#Induce a edge subgraph from edge 0, edge 1 and edge 3 from the original graph
sg2 = g.edge_subgraph([0, 1, 3])

In [12]:
print(sg1.ndata[dgl.NID]) #Print Node IDs of the Subgraph 1
print(sg1.edata[dgl.EID]) #Print Edge IDs of the Subgraph 1

print(sg2.ndata[dgl.NID]) #Print Node IDs of the Subgraph 2
print(sg2.edata[dgl.EID]) #Print Edge IDs of the Subgraph 2

tensor([0, 1, 3])
tensor([0, 2])
tensor([0, 1, 2, 4])
tensor([0, 1, 3])


In [13]:
# The original node feature of each node in sg1
print(sg1.ndata['x'])

tensor([[ 0.0974, -1.3089,  2.1166],
        [ 0.4933,  1.3394,  0.7622],
        [-1.0759,  0.2161,  0.0928]])


In [14]:
## Adding Reverse Edges to a Graph to convert from Unidirectional to Bidirectional
newg = dgl.add_reverse_edges(g)

print(newg.edges())

(tensor([0, 0, 0, 0, 0, 1, 2, 3, 4, 5]), tensor([1, 2, 3, 4, 5, 0, 0, 0, 0, 0]))


In [15]:
## Loading and Saving Graphs
dgl.save_graphs('graph.dgl', g)
dgl.save_graphs('multi_graphs.dgl', [g, sg1, sg2])

(g), _ = dgl.load_graphs('graph.dgl')
print(g)

(g, sg1, sg2), _ = dgl.load_graphs('multi_graphs.dgl')
print(sg1)
print(sg2)

[Graph(num_nodes=6, num_edges=5,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32)}
      edata_schemes={})]
Graph(num_nodes=3, num_edges=2,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'x': Scheme(shape=(3,), dtype=torch.float32)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)})
Graph(num_nodes=4, num_edges=3,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'x': Scheme(shape=(3,), dtype=torch.float32)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)})
